[tool.black]
line-length = 120

[tool.poetry]
name = "libraries-repository-engine"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^23.1"
codespell = "^2.2.2"
flake8 = "^6.0.0"
invoke = "^2.0.0"
pep8-naming = "^0.13.3"
pytest = "^7.2.1"
yamllint = "^1.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
