[tool.black]
line-length = 120

[tool.poetry]
name = "libraries-repository-engine"
version = "0.0.0"
description = ""
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.10"
codespell = "^2.2.2"
flake8 = "^5.0.4"
invoke = "^1.7.3"
pep8-naming = "^0.13.2"
pytest = "^7.1.3"
yamllint = "^1.28.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
