name: Check Go

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-go.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**.go"
  pull_request:
    paths:
      - ".github/workflows/check-go.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**.go"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to tools.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check-errors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check for errors
        run: task go:vet

  check-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check style
        run: task --silent go:lint

  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Format code
        run: task go:format

      - name: Check formatting
        run: git diff --color --exit-code

  check-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check whether any tidying was needed
        run: git diff --color --exit-code
