name: Test Go

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yml"
      - "**.go"
  pull_request:
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yml"
      - "**.go"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Build application
        run: task go:build

      - name: Save binary as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: libraries-repository-engine
          name: libraries-repository-engine

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Run tests
        run: task go:test
