# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/test-go-task.md
name: Test Go

env:
  # See: https://github.com/actions/setup-go/tree/v2#readme
  GO_VERSION: "1.16"

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "**/go.mod"
      - "**/go.sum"
      - "Taskfile.ya?ml"
      - "**/testdata/**"
      - "**.go"
  pull_request:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "**/go.mod"
      - "**/go.sum"
      - "Taskfile.ya?ml"
      - "**/testdata/**"
      - "**.go"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Build application
        run: task go:build

      - name: Save binary as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: libraries-repository-engine
          name: libraries-repository-engine

  test:
    name: test (${{ matrix.module.path }} - ${{ matrix.operating-system }})

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - ubuntu-latest
        module:
          - path: ./

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Arduino Lint
        run: |
          ARDUINO_LINT_INSTALLATION_PATH="${{ runner.temp }}/arduino-lint"
          mkdir --parents "$ARDUINO_LINT_INSTALLATION_PATH"
          curl \
            -fsSL \
            https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh \
          | \
          BINDIR="$ARDUINO_LINT_INSTALLATION_PATH" \
          sh

          # Add installation folder to path to path
          echo "$ARDUINO_LINT_INSTALLATION_PATH" >> "$GITHUB_PATH"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Run tests
        env:
          GO_MODULE_PATH: ${{ matrix.module.path }}
        run: task go:test
